#!/usr/bin/env python3
"""
Full Mortgage Analysis Runner - Headless Mode
Runs the complete mortgage analysis using the generated combinations file
"""

import os
import sys
import glob
from run_comprehensive_mortgage_analysis import run_comprehensive_analysis

def find_latest_combinations_file():
    """Find the most recent mortgage combinations file"""
    # Look for different possible patterns
    patterns = [
        'mortgage_combinations_*.json',  # Generated by the script
        'mortgage_combinations.json',    # Direct file
    ]
    
    all_files = []
    for pattern in patterns:
        files = glob.glob(pattern)
        all_files.extend(files)
    
    if not all_files:
        print("Error: No mortgage combinations file found!")
        print("Please run generate_mortgage_combinations.py first to create the combinations file.")
        return None
    
    # Sort by modification time and get the most recent
    all_files.sort(key=os.path.getmtime, reverse=True)
    latest_file = all_files[0]
    print(f"Using combinations file: {latest_file}")
    return latest_file

def main():
    """Main function to run full analysis in headless mode"""
    print("="*80)
    print("FULL MORTGAGE ANALYSIS - HEADLESS MODE")
    print("="*80)
    
    # Find the combinations file
    combinations_file = find_latest_combinations_file()
    if not combinations_file:
        sys.exit(1)
    
    # Check if the file exists and has content
    if not os.path.exists(combinations_file):
        print(f"Error: File {combinations_file} not found!")
        sys.exit(1)
    
    file_size = os.path.getsize(combinations_file)
    if file_size == 0:
        print(f"Error: File {combinations_file} is empty!")
        sys.exit(1)
    
    print(f"File size: {file_size:,} bytes")
    
    # Run the analysis in headless mode
    print("\nStarting full analysis in headless mode...")
    print("This will process all combinations and may take 30-45 minutes.")
    print("Progress will be tracked automatically.")
    print("You can check progress anytime with: python3 run_comprehensive_mortgage_analysis.py --status")
    print("\nPress Ctrl+C to stop the analysis (it can be resumed later)")
    
    try:
        success = run_comprehensive_analysis(
            combinations_file=combinations_file,
            headless=True,  # Run in headless mode
            max_combinations=None,  # Process all combinations
            tracking_file="processed_combinations.json"
        )
        
        if success:
            print("\n" + "="*80)
            print("ANALYSIS COMPLETED SUCCESSFULLY!")
            print("="*80)
            print("Check the following directories for results:")
            print("  - payments_files/ (detailed monthly payment data)")
            print("  - summary_files/ (summary statistics)")
            print("  - processed_combinations.json (progress tracking)")
        else:
            print("\n" + "="*80)
            print("ANALYSIS FAILED!")
            print("="*80)
            print("Check the error messages above for details.")
            sys.exit(1)
            
    except KeyboardInterrupt:
        print("\n" + "="*80)
        print("ANALYSIS INTERRUPTED BY USER")
        print("="*80)
        print("Progress has been saved. You can resume later by running this script again.")
        print("The system will automatically skip already processed combinations.")
        sys.exit(0)
    except Exception as e:
        print(f"\nUnexpected error: {e}")
        print("Analysis failed. Check the error messages above.")
        sys.exit(1)

if __name__ == "__main__":
    main() 